services:
  - type: web
    name: minha-api-senai
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: node dist/server.js
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production